server:
  port: 8088
spring:
  profiles:
    active: prod
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show-sql: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/biletterdb
batch:
  size: 1000
service-provider:
  url: https://hub.hackload.kz/event-provider/common