server:
  port: 8088
spring:
  profiles:
    active: prod
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true

  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/biletterdb